# Links

- [Liu 2025: Cell type–specific 3D-genome organization and transcription regulation in the brain](https://www.science.org/doi/10.1126/sciadv.adv2067)
- [GitHub repo for Liu 2025](https://github.com/ZhuangLab/Chromatin_Analysis_MOp/)

# Processing FOF-CT files

## Docs

- [Docs: 4DN FISH Omics Format - Chromatin Tracing (FOF-CT)](https://fish-omics-format.readthedocs.io/en/latest/)
- [DNA-Spot/Trace Data core table](https://fish-omics-format.readthedocs.io/en/latest/core.html)
- [Cell Data table](https://fish-omics-format.readthedocs.io/en/latest/cell.html)

Note: FOV = 'fields of view'

## Examining files

### Examining DNA-Spot/Trace Data core table

In [16]:
%%bash

sample_dir="$HOME/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt"
cd "$sample_dir/biorep1_techrep1"

# # ==== Examine header info

# Number of header lines
echo $(grep '^["#]' dna_spot_trace_core.csv | wc -l)" header lines, including col labels"
echo $(grep ',,,' dna_spot_trace_core.csv | wc -l)" header lines, excluding col labels"

# Column labels
echo -e "\nColumn labels:"
grep -v ',,,' dna_spot_trace_core.csv | head -n 1 | sed 's/.*(//;s/).*//' | tr ',' '\n' | awk 'BEGIN{c=1}{print c "\t" $0; c += 1}'

# Column label desc
echo -e "\nColumn label desc:"
grep ',,,' dna_spot_trace_core.csv | tail -n 7 | sed 's/,,*//g'

23 header lines, including col labels
22 header lines, excluding col labels

Column labels:
1	Spot_ID
2	Trace_ID
3	X
4	Y
5	Z
6	Chrom
7	Chrom_Start
8	Chrom_End
9	Chrom_order
10	Cell_ID
11	FOV_ID
12	CellID_byFOV
13	RNA_experiment_ID
14	DNA_experiment_ID
15	Sample_ID

Column label desc:
##XYZ_unit=nm
#Spot_ID:unique DNA spot identifier across 4dn_FOF-CT_core and 4dn_FOF-CT_demultiplxeing for the same replicate
#Trace_ID:number format as fovXX_cellXX_chrXX_chromatidXX
#Chrom_order:order of DNA region on its respective chromosome
#Cell_ID:unique cell identifier across the datatables
#FOV:FOV ID across datatables for the same replicate
#CellID_byFOVspecific cell identifier relative to the FOV

In [9]:
%%bash

sample_dir="$HOME/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt"
cd "$sample_dir/biorep1_techrep1"

# ==== Check uniqueness of cells
echo -e "Uniqueness of cells"
echo $(grep -v '^["#]' dna_spot_trace_core.csv | cut -d ',' -f 10-12 | sort | uniq | wc -l)" unique combos of 'Cell_ID, FOV_ID, CellID_byFOV'"
echo $(grep -v '^["#]' dna_spot_trace_core.csv | cut -d ',' -f 10 | sort | uniq | wc -l)" unique 'Cell_ID'"
echo $(grep -v '^["#]' dna_spot_trace_core.csv | cut -d ',' -f 11-12 | sort | uniq | wc -l)" unique combos of 'FOV_ID, CellID_byFOV'"
echo $(grep -v '^["#]' dna_spot_trace_core.csv | cut -d ',' -f 12 | sort | uniq | wc -l)" unique 'CellID_byFOV'"
echo $(grep -v '^["#]' dna_spot_trace_core.csv | cut -d ',' -f 11 | sort | uniq | wc -l)" unique 'FOV_ID'"


# ==== Check uniqueness of rows
echo -e "\nUniqueness of rows"
echo $(grep -v '^["#]' dna_spot_trace_core.csv | wc -l)" unique 'rows'"
echo $(grep -v '^["#]' dna_spot_trace_core.csv | cut -d ',' -f 1 | sort | uniq | wc -l)" unique 'Spot_ID'"
echo $(grep -v '^["#]' dna_spot_trace_core.csv | cut -d ',' -f 2,9 | sort | uniq | wc -l)" unique combos of 'Trace_ID, Chrom_order'"

Uniqueness of cells
12725 unique combos of 'Cell_ID, FOV_ID, CellID_byFOV'
12725 unique 'Cell_ID'
12725 unique combos of 'FOV_ID, CellID_byFOV'
253 unique 'CellID_byFOV'
148 unique 'FOV_ID'

Uniqueness of rows
8258329 unique 'rows'
8258329 unique 'Spot_ID'
8258329 unique combos of 'Trace_ID, Chrom_order'

In [11]:
%%bash

sample_dir="$HOME/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt"
cd "$sample_dir/biorep1_techrep1"

# ==== Check that the chromosome component of 'Trace_ID' (fovXX_cellXX_chrXX_chromatidXX) corresponds to the 'Chrom' column
ndiff=$(awk -F '[,_]' '{ if ($1 !~ /^[#"]/){ gsub(/chr/, "", $9); if ($4 != $9) { print $4 "\t" $9 } } }' dna_spot_trace_core.csv | wc -l)
if [[ $ndiff -eq 0 ]]; then
    echo "✓ Chromosome component of 'Trace_ID' (fovXX_cellXX_chrXX_chromatidXX) corresponds to the 'Chrom' column"
else
    echo "✗ Chromosome component of 'Trace_ID' (fovXX_cellXX_chrXX_chromatidXX) does NOT correspond to the 'Chrom' column for $ndiff lines"
fi


# ==== Examine size of each region
echo -e "\nSize of each region: (1st 10 lines)"
awk -F ',' '{ if ($1 !~ /^[#"]/){ print $8 - $7 } }' dna_spot_trace_core.csv | head

✓ Chromosome component of 'Trace_ID' (fovXX_cellXX_chrXX_chromatidXX) corresponds to the 'Chrom' column

Size of each region: (1st 10 lines)
8595
8623
11242
10504
8112
9570
8405
7269
8405
7187

### Examining Cell Data table

In [55]:
%%bash

sample_dir="$HOME/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt"
cd "$sample_dir/biorep1_techrep1"

# # ==== Examine header info

# Number of header lines
echo $(grep '^["#]' cell_data.csv | wc -l)" header lines, including col labels"
echo $(grep ',,,' cell_data.csv | wc -l)" header lines, excluding col labels"

# Column labels
ncols_gene=$( grep -v ',,,' cell_data.csv | head -n 1 | sed 's/.*neuron_identity,//' | tr ',' '\n' | wc -l )
echo -e "\nColumn labels (excluding $ncols_gene gene xp columns):"
grep -v ',,,' cell_data.csv | head -n 1 | sed 's/neuron_identity,.*/neuron_identity/;s/.*(//;s/).*//' | tr ',' '\n' | awk 'BEGIN{c=1}{print c "\t" $0; c += 1}'

# Column label desc
echo -e "\nColumn label desc:"
grep ',,,' cell_data.csv | tail -n 7 | sed 's/,,*//g'

23 header lines, including col labels
22 header lines, excluding col labels

Column labels (excluding 242 gene xp columns):
1	Cell_ID
2	FOV_ID
3	cell_volume_from_merlin
4	cell_center_x_global
5	cell_center_y_global
6	RNA_experiment_ID
7	Sample_ID
8	cluster_subclass
9	cluster_class
10	neuron_identity

Column label desc:
##XYZ_unit=micron
#Cell_ID:unique cell identifier across the datatables
#cell_center_x_global:x coordinate of the cell relative to all cells for the experiment replicate
#cell_center_y_global:y coordinate of the cell relative to all cells for the experiment replicate
#cluster_subclass:transcriptionally defined cell cluster lable at subclass level
#cluster_class:transcriptionally defined cell cluster lable at a higer level
"#RNA count for gene A:decoded raw RNA count for gene A (e.g. gene 1700022I11Rik)"

In [116]:
%%bash

sample_dir="$HOME/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt"
biorep="$sample_dir/biorep1_techrep1"

# # ==== Count cells & clusters

# Number of cells
echo -e $(grep -v '^["#]' "$biorep/cell_data.csv" | wc -l)" cells (lines)"

# Number of clusters
nclust_sub=$( grep -v '^["#]' "$biorep/cell_data.csv" | cut -d ',' -f 8 | sort | sed 's/ //g' | uniq -c | awk '{ print $1 "\t" $2 }' | sort -k1,1nr )
echo -e "\n"$(echo -e "$nclust_sub" | wc -l)" clusters (only via 'cluster_subclass')"
nclust=$( grep -v '^["#]' "$biorep/cell_data.csv" | cut -d ',' -f 8-10 | sort | sed 's/ //g' | uniq -c | awk '{ print $1 "\t" $2 }' | sort -k1,1nr )
echo -e $(echo -e "$nclust" | wc -l)" clusters (via combo of 'cluster_subclass, cluster_class, neuron_identity'):"
echo -e "$nclust"

# Number of clusters (only via cluster_class)
nclust_class=$( grep -v '^["#]' "$biorep/cell_data.csv" | cut -d ',' -f 9 | sort | sed 's/ //g' | uniq -c | awk '{ print $1 "\t" $2 }' | sort -k1,1nr )
echo -e "\n"$(echo -e "$nclust_class" | wc -l)" clusters (only via 'cluster_class')"
echo -e "$nclust_class"

17856 cells (lines)

22 clusters (only via 'cluster_subclass')
22 clusters (via combo of 'cluster_subclass, cluster_class, neuron_identity'):
2184	L2/3IT,Gluta,Neuronal
1803	Astro,Astro,Non-Neuronal
1741	L6CT,Gluta,Neuronal
1474	L5IT,Gluta,Neuronal
1294	other,other,other
1088	L5ET,Gluta,Neuronal
1039	Endo,Endo,Non-Neuronal
1029	L4/5IT,Gluta,Neuronal
1029	OPC,Oligo,Non-Neuronal
972	Oligo,Oligo,Non-Neuronal
789	L6IT,Gluta,Neuronal
711	Micro,Micro,Non-Neuronal
549	Pvalb,GABA,Neuronal
391	L5/6NP,Gluta,Neuronal
380	Sst,GABA,Neuronal
274	VLMC,VLMC,Non-Neuronal
266	Peri,Peri,Non-Neuronal
205	Vip,GABA,Neuronal
198	SMC,SMC,Non-Neuronal
185	L6b,Gluta,Neuronal
180	Lamp5,GABA,Neuronal
75	Sncg,GABA,Neuronal

10 clusters (only via 'cluster_class')
8881	Gluta
2001	Oligo
1803	Astro
1389	GABA
1294	other
1039	Endo
711	Micro
274	VLMC
266	Peri
198	SMC

## Extracting relevant information

In [51]:
%%bash

sample_dir="$HOME/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt"

# ==== Reformat relevant columns from 'cell_data.csv':
# 1 	Cell_ID
# 8 	cluster_subclass
# 9 	cluster_class
# 10	neuron_identity

# # Testing on one biorep
# biorep="$sample_dir/biorep1_techrep1"
# rep_id=$(basename "$biorep" | sed 's/_/./;s/[A-z]*//g' )
# awk -F ',' -v rep_id="$rep_id" 'BEGIN{OFS=","}{ if ($(NF-1) != ""){ 
#     if ($1 ~ /Cell_ID/){ print "#rep_id", "#" tolower($10), "#" tolower($9), "#" tolower($8), "#cell_id" }
# 	  else { gsub(/ /, "_", $8); print rep_id, tolower($10), tolower($9), tolower($8), $1 } } }' "$biorep/cell_data.csv" | sort -t ',' -k2,5 | head  | tr ',' '\t'


for biorep in $( find "$sample_dir" -type d -name 'biorep*_techrep*' ); do
	if [ -f "$biorep/cells.csv" ]; then
		continue
	fi
    basename "$biorep"
	if [ ! -f "$biorep/cell_data.csv" ] & [ -f "$biorep/cell_data.csv.gz" ]; then
		gunzip "$biorep/cell_data.csv.gz"
	fi

    rep_id=$(basename "$biorep" | sed 's/_/./;s/[A-z]*//g' )
    awk -F ',' -v rep_id="$rep_id" 'BEGIN{OFS=","}{ if ($(NF-1) != ""){ 
        if ($1 ~ /Cell_ID/){ print "#rep_id", "#" tolower($10), "#" tolower($9), "#" tolower($8), "#cell_id" }
        else { gsub(/ /, "_", $8); gsub(/\//, "-", $8); print rep_id, tolower($10), tolower($9), tolower($8), $1 } } }' "$biorep/cell_data.csv" | sort -t ',' -k2,5 > "$biorep/cells.csv"

	gzip "$biorep/cell_data.csv"
done

biorep3_techrep1
biorep1_techrep1
biorep2_techrep1
biorep3_techrep2

In [222]:
%%bash

sample_dir="$HOME/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt"

# ==== Reformat relevant columns from 'dna_spot_trace_core.csv':
# 2 	Trace_ID  (fovXX_cellXX_chrXX_chromatidXX)
# 3 	X
# 4 	Y
# 5 	Z
# 7 	Chrom_Start
# 8 	Chrom_End
# 9 	Chrom_order
# 10	Cell_ID

# # Testing on one biorep
# biorep="$sample_dir/biorep1_techrep1"
# rep_id=$(basename "$biorep" | sed 's/_/./;s/[A-z]*//g' )
# awk -F ',' -v rep_id="$rep_id" 'BEGIN{OFS=","}{ if ($(NF-1) != ""){ 
# 	df_cell_desc=$9","$7","$8","$3","$4","$5;
# 	if ($2 == "Trace_ID"){ molecule="#rep_id,#cell_id,#chrom,#trace_id"; df_cell_desc="#"gensub(/,/, ",#", "g", tolower(df_cell_desc)) }
# 	else { molecule=rep_id","$10","gensub(/.+_.+_(.+)_(.+)/, "\\1,\\2", "g", $2) };
# 	print molecule, df_cell_desc } }' "$biorep/dna_spot_trace_core.csv" | sort -t ',' -k2,2 -k3,3n -k4,4n -k5,5n | head | tr ',' '\t' | sed -r 's/(\.[0-9])[0-9]*/\1/g'


for biorep in $( find "$sample_dir" -type d -name 'biorep*_techrep*' ); do
	if [ -f "$biorep/dna_merfish.csv" ]; then
		continue
	fi
    basename "$biorep"
	if [ ! -f "$biorep/dna_spot_trace_core.csv" ] & [ -f "$biorep/dna_spot_trace_core.csv.gz" ]; then
		gunzip "$biorep/dna_spot_trace_core.csv.gz"
	fi

    rep_id=$(basename "$biorep" | sed 's/_/./;s/[A-z]*//g' )
    awk -F ',' -v rep_id="$rep_id" 'BEGIN{OFS=","}{ if ($(NF-1) != ""){ 
    	df_cell_desc=$9","$7","$8","$3","$4","$5;
    	if ($2 == "Trace_ID"){ molecule="#rep_id,#cell_id,#chrom,#trace_id"; df_cell_desc="#"gensub(/,/, ",#", "g", tolower(df_cell_desc)) }
    	else { molecule=rep_id","$10","gensub(/.+_.+_(.+)_(.+)/, "\\1,\\2", "g", $2) };
    	print molecule, df_cell_desc } }' "$biorep/dna_spot_trace_core.csv" | sort -t ',' -k2,2 -k3,3n -k4,4n -k5,5n > "$biorep/dna_merfish.csv"

	gzip "$biorep/dna_spot_trace_core.csv"
done

## Consolidating cell data across all replicates

In [897]:
%%bash

sample_dir="$HOME/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt"

allreps_dir="$sample_dir/all_reps"
cells_file="$allreps_dir/cells.csv"

# ==== Consolidate cells across all replicates

mkdir -p "$allreps_dir"

# Write header
head -n 1 $(find "$sample_dir" -type f -path '*/biorep*_techrep*/cells.csv' | head -n 1) > "$cells_file"

# Write cells (but only if DNA-MERFISH data exists for that cell)
# grep -r "$sample_dir/"biorep*_techrep*/cells.csv -hve '^#' | sort -t ',' -k1,5 >> "$cells_file" # Write all cells - OLD
for biorep in $( find "$sample_dir" -type d -name 'biorep*_techrep*' ); do
    join -t ',' -1 5 -2 1 --header --check-order \
    <( sort -t ',' -k 5,5 "$biorep/cells.csv" ) \
    <( cut -d ',' -f 2 "$biorep/dna_merfish.csv" | sort | uniq ) \
    | awk -F',' 'BEGIN{OFS=","}{if ($1 !~ /^#/) {print $2, $3, $4, $5, $1}}' >> "$cells_file"
done

# Sort cells in 'all reps' file
sort -t ',' -k1,5 -o "$cells_file" "$cells_file"

# Total cells
echo "Total cells (across all experiments): "$( grep -r "$sample_dir/"biorep*_techrep*/cells.csv -hve '^#' | wc -l )
echo "Total cells (that are present in DNA-MERFISH experiments): "$( grep -v '^#' "$cells_file" | wc -l )

Total cells (across all experiments): 62732
Total cells (that are present in DNA-MERFISH experiments): 46295

In [899]:
%%bash

sample_dir="$HOME/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt"

allreps_dir="$sample_dir/all_reps"
cells_file="$allreps_dir/cells.csv"

# ==== Count cells & clusters across all replicates

# Number of cells
echo -e $(grep -v '^["#]' "$cells_file" | wc -l)" lines in "$(basename "$cells_file")
echo -e $(grep -v '^["#]' "$cells_file" | cut -d ',' -f5 | sort | uniq | wc -l)" unique cells in "$(basename "$cells_file")

# Number of clusters
nclust=$( grep -v '^["#]' "$cells_file" | cut -d ',' -f 4 | sort | sed 's/ //g' | uniq -c | awk '{ print $1 "\t" $2 }' | sort -k1,1nr )
echo -e "\n"$(echo -e "$nclust" | wc -l)" clusters (only via 'cluster_subclass')"
nclust_trio=$( grep -v '^["#]' "$cells_file" | cut -d ',' -f 2-4 | sort | sed 's/ //g' | uniq -c | awk '{ print $1 "\t" $2 }' | sort -k1,1nr )
echo -e $(echo -e "$nclust_trio" | wc -l)" clusters (via combo of 'cluster_subclass, cluster_class, neuron_identity'):"
echo -e "$nclust_trio"

echo -e "\nNumber of (subclass-based) clusters with >= [cutoff] cells per cluster (ignoring 'other' cluster)"
for cutoff in 1000 2000 2500; do
    echo -e "$nclust" | awk -vcutoff="$cutoff" 'BEGIN{ nlines=0; total=0 } \
        {if (($1 >= cutoff) && ($2 != "other")){nlines += 1; total += $1}} \
        END{ print nlines" clusters with >= "cutoff" cells per cluster, total cells="total }'
done

# Number of clusters (only via cluster_class)
nclust_class=$( grep -v '^["#]' "$cells_file" | cut -d ',' -f 3 | sort | sed 's/ //g' | uniq -c | awk '{ print $1 "\t" $2 }' | sort -k1,1nr )
echo -e "\n"$(echo -e "$nclust_class" | wc -l)" clusters (only via 'cluster_class')"
echo -e "$nclust_class"

46295 lines in cells.csv
46295 unique cells in cells.csv

22 clusters (only via 'cluster_subclass')
22 clusters (via combo of 'cluster_subclass, cluster_class, neuron_identity'):
6469	non-neuronal,oligo,oligo
5463	neuronal,gluta,l6_ct
4830	non-neuronal,astro,astro
4373	neuronal,gluta,l2-3_it
3687	non-neuronal,endo,endo
3370	neuronal,gluta,l4-5_it
2659	neuronal,gluta,l5_it
2510	neuronal,gluta,l6_it
1867	non-neuronal,oligo,opc
1856	non-neuronal,micro,micro
1637	neuronal,gluta,l5_et
1338	neuronal,gaba,pvalb
1036	neuronal,gluta,l6b
969	neuronal,gaba,sst
939	non-neuronal,peri,peri
751	neuronal,gluta,l5-6_np
600	non-neuronal,vlmc,vlmc
555	non-neuronal,smc,smc
465	neuronal,gaba,vip
455	neuronal,gaba,lamp5
294	other,other,other
172	neuronal,gaba,sncg

Number of (subclass-based) clusters with >= [cutoff] cells per cluster (ignoring 'other' cluster)
13 clusters with >= 1000 cells per cluster, total cells=41095
8 clusters with >= 2000 cells per cluster, total cells=33361
8 clusters with >= 2500 cells per cluster, total cells=33361

10 clusters (only via 'cluster_class')
21799	gluta
8336	oligo
4830	astro
3687	endo
3399	gaba
1856	micro
939	peri
600	vlmc
555	smc
294	other

## Segregating DNA-MERFISH data per cluster (excluding 'other' cluster)

In [900]:
%%bash

sample_dir="$HOME/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt"
ncells_cutoff=2000

allreps_dir="$sample_dir/all_reps"
cells_file="$allreps_dir/cells.csv"

# ==== Get cells belonging to 'top' clusters (clusters with >= cutoff cells)
clusters_all=$( grep -v '^["#]' "$cells_file" | cut -d ',' -f 4 | sort | sed 's/ //g' | uniq -c | awk '{ print $1 "\t" $2 }' | sort -k1,1nr )
clusters_top=$( echo -e "$clusters_all" | awk -vcutoff="$ncells_cutoff" '{if (($1 >= cutoff) && ($2 != "other")) {print $2}}' )
nclust_top=$( echo -e "$clusters_top" | wc -l )

clusters_top_re="(^"$( echo -e "$clusters_top" | tr '\n' '|' | sed 's/|$//;s/|/$|^/g;s:/:.:g' )"$)"
cells_topclust_file="$allreps_dir/cells.top${nclust_top}clust.csv"
    
head -n 1 "$cells_file" | cut -d ',' -f 1,4,5 > "$cells_topclust_file"
awk -F',' 'BEGIN{OFS=","}{ if ($4 ~ /'"$clusters_top_re"'/){ print $1, $4, $5 } }' "$cells_file"  >> "$cells_topclust_file"

# Count number of cells matching one of the chosen clusters
echo "Total cells across all chosen clusters (per "$(basename "$cells_topclust_file")"): "$( cut -d ',' -f 3 "$cells_topclust_file" | uniq | grep -v '^#' | wc -l )

                                                                                            
# ==== Label DNA MERFISH data from cells belonging to 'top' clusters (clusters with >= cutoff cells); discard data for other cells
dna_allreps_file="$allreps_dir/dna_merfish.top${nclust_top}clust.csv"

# Make header for dna_allreps_file
paste -d ',' \
    <( echo "#cell_id" ) \
    <( head -n 1 $(find "$sample_dir" -type f -path '*/biorep*_techrep*/dna_merfish.csv' | head -n 1 ) | sed 's/#cell_id,//' ) \
    <( head -n 1 "$cells_topclust_file" | cut -d ',' -f 2    ) > "$dna_allreps_file"

# Assign cluster label to DNA MERFISH data (for cells in the chosen clusters)
for biorep in $( find "$sample_dir" -type d -name 'biorep*_techrep*' ); do
    rep_id=$(basename "$biorep" | sed 's/_/./;s/[A-z]*//g' )
    awk -F ',' -v rep_id="$rep_id" '{ if (($1 == rep_id) || ($1 ~ /rep_id/)){ print $2 "," $3 } }' "$cells_topclust_file" | sort -t ',' -k 2b,2 | \
        join -t ',' -j 2 --header --check-order "$biorep/dna_merfish.csv" - | grep -v '^#' >> "$dna_allreps_file"
done

# Count number of cells matching one of the chosen clusters
echo "Total cells across all chosen clusters (per "$(basename "$dna_allreps_file")"): "$( cut -d ',' -f 1 "$dna_allreps_file" | uniq | grep -v '^#' | wc -l )

                                                                                      
# # ==== Segregate DNA MERFISH data by cluster

# Make directories per cluster, write header for sorted dna_merfish file
for cluster in $clusters_top; do
    mkdir -p "$allreps_dir/cluster/$cluster"
    head -n 1 "$dna_allreps_file" | cut -d ',' -f 1-10 > "$allreps_dir/cluster/$cluster/dna_merfish.$cluster.csv"
done

# Segregate DNA MERFISH data
awk -F',' -v outdir="$allreps_dir" 'BEGIN{OFS=","}{ if ($1 !~ /^#/) \
    { print $1, $2, $3, $4, $5, $6, $7, $8, $9, $10 >> outdir"/cluster/"$11"/dna_merfish."$11".csv" } }' "$dna_allreps_file"

# Count number of cells matching each of the chosen clusters
echo -e "\nCells per cluster:"
ncells_total=0
for cluster in $clusters_top; do
    ncells=$( cut -d ',' -f 1 "$allreps_dir/cluster/$cluster/dna_merfish.$cluster.csv" | uniq | grep -v '^#' | wc -l )
    echo "  $cluster: $ncells cells"
    ncells_total=$(($ncells_total + $ncells)) 
done
echo "TOTAL: $ncells_total cells"

Total cells across all chosen clusters (per cells.top8clust.csv): 33361
Total cells across all chosen clusters (per dna_merfish.top8clust.csv): 33361

Cells per cluster:
oligo: 6469 cells
l6_ct: 5463 cells
astro: 4830 cells
l2-3_it: 4373 cells
endo: 3687 cells
l4-5_it: 3370 cells
l5_it: 2659 cells
l6_it: 2510 cells
TOTAL: 33361 cells

## Characterizing the data

In [ ]:
%%bash

sample_dir="$HOME/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt"

allreps_dir="$sample_dir/all_reps"
clusters_dir="$allreps_dir/cluster"

cluster="astro"
cluster_file="$clusters_dir/$cluster/dna_merfish.$cluster.csv"

# All columns: 1=cell_id,  2=rep_id,  3=chrom,  4=trace_id,  5=chrom_order,  6=chrom_start,  7=chrom_end,  8=x,  9=y,  10=z

echo -e "\n\n==== QUESTION: Can a locus on a given 'chrom' be uniquely identified by either 'chrom_order', 'chrom_start', or 'chrom_end'? Or do you need some combo thereof?"

echo -e "\nInstances where a locus has the same start location but different end location (expected result=0):"
# Cols: #chrom,#chrom_start,#chrom_end
cut -d ',' -f 3,6,7 "$cluster_file" | sort | uniq | cut -d ',' -f 1-2 | uniq -d | wc -l

echo -e "\nInstances where a locus has the same start/end location but different value for 'chrom_order' (expected result=0):"
# Cols: #chrom,#chrom_start,#chrom_end
cut -d ',' -f 3,5,6,7 "$cluster_file" | sort | uniq | cut -d ',' -f 1-2 | uniq -d | wc -l

echo -e "\n\n==== CHARACTERIZING THE DATA"

echo -e "\nNumber of cells with data for each locus (on 1+ traces):"
# Cols: #cell_id,#chrom,#chrom_start,#chrom_end
cut -d ',' -f 1,3,6,7 "$cluster_file" | sort | uniq | cut -d ',' -f 1 | uniq -c | awk '!/#/ {print $1}' | sort -k1,1nr | pymath

echo -e "\nNumber of loci associated with each traceID:\nnum_loci\ttraceID"
# Cols: #chrom,#trace_id,#chrom_start,#chrom_end
cut -d ',' -f 3,4,6,7 "$cluster_file" | sort | uniq | cut -d ',' -f 2 | sort | uniq -c | awk '!/#/ {print $1 "\t\t" $2}' | sort -k1,1nr

echo -e "\nNumber of cells associated with each traceID:\nnum_cells\ttraceID"
# Cols: #cell_id,#trace_id
cut -d ',' -f 1,4 "$cluster_file" | sort | uniq | cut -d ',' -f 2 | sort | uniq -c | awk '!/#/ {print $1 "\t\t" $2}' | sort -k1,1nr

echo -e "\n\n==== QUESTION: Are there ever cases where a single copy of a single homolog of a single chromosome is represented by 2+ traces?"
#echo "If (A) and (B) below are identical, then the answer is 'no', otherwise its a 'maybe'..."
echo "Gotta be honest, the below tests don't really answer this question"

echo -e "\n(A) Number of cell-locus pairs associated with each traceID:\nnum_cell-locus_pairs\ttraceID"
# Cols: #cell_id,#chrom,#trace_id,#chrom_start,#chrom_end
# 1. Get unique cell-locus-traces
# 2. Number of cell-locus pairs per trace_ID
cut -d ',' -f 1,3,4,6,7 "$cluster_file" | sort | uniq | \
    cut -d ',' -f 3 | sort | uniq -c | awk '!/#/ {print $1 "\t\t\t" $2}' | sort -k1,1nr 

echo -e "\n(B) Number copies of each cell-locus pair:\nnum_cell-locus_pairs\tnum_copies_of_given_pair"
# # Cols: #cell_id,#chrom,#trace_id,#chrom_start,#chrom_end
# 1. Get unique cell-locus-traces
# 2. Number of unique traces per cell-locus pair
# 3. How often we see the given number of unique traces per cell-locus pair
cut -d ',' -f 1,3,4,6,7 "$cluster_file" | sort | uniq | \
    cut -d ',' -f 1,2,4,5 | sort | uniq -c | \
    awk '!/#/ {print $1}' | sort | uniq -c | awk '!/#/ {print $1 "\t\t\t" $2}' | sort -k1,1nr  # TODO is this correct?

## Choose loci 2.5Mb apart

In [811]:
import os
import pandas as pd
import numpy as np


def get_diff_from_median_offset(df):
    df['offset_vs_med'] = df.offset - df.offset.median()
    return df


def get_gaps_by_mids(df):
    df['gap_from_prev'] = np.nan
    df['gap_to_next'] = np.nan
    idx = df.index.values
    vals = df.loc[idx[1:], 'mid'].values - df.loc[idx[:-1], 'mid'].values
    df.loc[idx[1:], 'gap_from_prev'] = vals
    df.loc[idx[:-1], 'gap_to_next'] = vals
    return df


def get_evenly_spaced_loci(input_file, spacing=2.5, cutoff=0.05, outdir=None, verbose=True):
    loci = pd.read_csv(input_file, sep="\t", header=None, names=['chrom', 'start_bp', 'end_bp'])
    loci['chrom'] = loci.chrom.str.replace('chr', '', regex=False)
    loci = loci.sort_values(['chrom', 'start_bp', 'end_bp']).reset_index(drop=True)
    loci = loci[loci.chrom != 'Y']
    loci['locus_size'] = (loci.end_bp - loci.start_bp) / 1e6  # Mb
    loci['mid'] = loci[['start_bp', 'end_bp']].mean(axis=1) / 1e6  # Mb
    loci['offset'] = loci.mid % spacing

    if verbose >= 2:
        print("\nSIZES OF LOCI (bp):", flush=True)
        print((loci.locus_size.describe()).round().astype(int).to_string(), flush=True)
        print(f"{(loci.locus_size > 0.02).sum() / len(loci) * 100:.3g}% of loci are > 20kb", flush=True)
        # print(loci.loc[loci.locus_size > 0.02, ['start', 'end', 'locus_size', 'gap_from_prev', 'gap_to_next']])
        print("\n\nLOCI OFFSETS (compared to median offset):", flush=True)
        print((loci.offset_vs_med).describe().to_string(), flush=True)

    loci = loci.groupby('chrom').apply(get_diff_from_median_offset, include_groups=False).reset_index(
        level=0)
    loci = loci.groupby('chrom').apply(get_gaps_by_mids, include_groups=False).reset_index(
        level=0)
    if verbose:
        print(f"{len(loci)} loci... gaps between loci:", flush=True)
        print(loci.gap_from_prev.describe().to_string(), flush=True)
    
    # For loci whose midpoints differ by <[cutoff], choose locus with smallest absolute deviation from median offset
    if verbose:
        print(("\nFor loci whose midpoints differ by <[cutoff], choose locus with smallest"
               " absolute deviation from median offset"), flush=True)
    while (loci.gap_to_next < cutoff).sum():
        gap_to_next_pass = loci.gap_to_next.isnull() | (loci.gap_to_next >= cutoff)
        gap_from_prev_pass = loci.gap_from_prev.isnull() | (loci.gap_from_prev >= cutoff)
        smallgap_prev = loci.loc[~gap_to_next_pass, 'offset_vs_med'].abs()
        smallgap_next = loci.loc[~gap_from_prev_pass, 'offset_vs_med'].abs()
        smallgap_argmin = np.stack([smallgap_prev.values, smallgap_next.values], axis=1).argmin(axis=1)
        smallgap_best = smallgap_prev.index + smallgap_argmin
        loci = loci[(gap_to_next_pass & gap_from_prev_pass) | (loci.index.isin(smallgap_best))].reset_index(drop=True)
        loci = loci.groupby('chrom').apply(get_gaps_by_mids, include_groups=False).reset_index(
            level=0)
        loci = loci.groupby('chrom').apply(get_diff_from_median_offset, include_groups=False).reset_index(
            level=0)
    if verbose:
        print(f"{len(loci)} loci... gaps between loci:", flush=True)
        print(loci.gap_from_prev.describe().to_string(), flush=True)
    
    # Remove loci whose absolute deviation form median offset >= [cutoff]
    if verbose:
        print("\nRemove loci whose absolute deviation form median offset >= [cutoff]", flush=True)
    loci = loci[(loci.offset_vs_med.abs() < cutoff)].copy()
    loci = loci.groupby('chrom').apply(get_gaps_by_mids, include_groups=False).reset_index(
        level=0)
    loci = loci.groupby('chrom').apply(get_diff_from_median_offset, include_groups=False).reset_index(
        level=0)
    if verbose:
        print(f"{len(loci)} loci... gaps between loci:", flush=True)
        print(loci.gap_from_prev.describe().to_string(), flush=True)
        print(f"\n{len(loci[loci.gap_from_prev > 4])} loci are spaced >4 Mb apart", flush=True)

    # Save
    if outdir is not None:
        os.makedirs(outdir, exist_ok=True)
        outfile = os.path.join(outdir, f"loci.spaced{spacing * 1000:g}kb.csv")
        print(f"\nSaving to: {outfile}", flush=True)
        loci.to_csv(outfile, index=False)

    return loci


sample_dir = "~/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt"
all_loci_file = os.path.join(sample_dir, 'supplementary/target_regions.bed.gz')
loci = get_evenly_spaced_loci(all_loci_file, spacing=2.5, cutoff=0.05, outdir=sample_dir, verbose=True)
loci

1981 loci... gaps between loci:
count    1961.000000
mean        1.289912
std         1.005944
min        -0.006165
25%         0.433977
50%         1.076219
75%         2.180035
max        12.502445

For loci whose midpoints differ by <[cutoff], choose locus with smallest absolute deviation from median offset
1940 loci... gaps between loci:
count    1920.000000
mean        1.317457
std         0.999483
min         0.050709
25%         0.468003
50%         1.097869
75%         2.217746
max        12.502445

Remove loci whose absolute deviation form median offset >= [cutoff]
987 loci... gaps between loci:
count    967.000000
mean       2.608568
std        0.664271
min        2.491560
25%        2.498452
50%        2.500004
75%        2.501743
max       12.502445

32 loci are spaced >4 Mb apart

Saving to: ~/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt/loci.spaced2500kb.csv

,chrom,start_bp,end_bp,locus_size,mid,offset,offset_vs_med,gap_from_prev,gap_to_next
0,1,3742742,3759944,0.017202,3.751343,1.251343,-0.003268,NaN,2.501121
1,1,6245958,6258969,0.013011,6.252464,1.252464,-0.002148,2.501121,2.497498
2,1,8740008,8759916,0.019908,8.749962,1.249962,-0.004649,2.497498,2.502718
5,1,11247744,11257616,0.009872,11.252680,1.252680,-0.001931,2.502718,2.497225
6,1,13741888,13757922,0.016034,13.749905,1.249905,-0.004706,2.497225,2.505740
...,...,...,...,...,...,...,...,...,...
1933,X,158749404,158759978,0.010574,158.754691,1.254691,0.002299,2.504721,2.498749
1934,X,161247067,161259813,0.012746,161.253440,1.253440,0.001048,2.498749,2.501180
1935,X,163750534,163758706,0.008172,163.754620,1.254620,0.002228,2.501180,2.499187
1936,X,166247682,166259932,0.012250,166.253807,1.253807,0.001415,2.499187,2.498010
1938,X,168746045,168757590,0.011545,168.751817,1.251817,-0.000575,2.498010,NaN

## Exploring the DNA-MERFISH dataset

In [438]:
import os
import pandas as pd
import numpy as np

sample_dir = "~/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt"
clusters_dir = os.path.join(sample_dir, "all_reps", "cluster")

cluster = "astro"
cluster_file = os.path.join(clusters_dir, f"{cluster}/dna_merfish.{cluster}.csv")

In [439]:
df = pd.read_csv(cluster_file, dtype={
    'cell_id': int, 'rep_id': float, 'chrom': str, 'trace_id': int, 'chrom_order': int,
    'chrom_start': int, 'chrom_end': int, 'x': float, 'y': float, 'z': float})
df.columns = [x.strip('#') for x in df.columns]

if 'hmlg' in df.columns:  # TODO temp fix
    df.rename({'hmlg': 'trace_id'}, axis=1, inplace=True)

In [541]:
df

,cell_id,rep_id,chrom,trace_id,chrom_order,chrom_start,chrom_end,x,y,z
0,100267022990578563888527231462820232415,3.1,X,1,8,38748472,38759587,77.503165,134.552984,2.967085
1,100267022990578563888527231462820232415,3.1,X,1,9,41244470,41259864,78.239118,134.450069,2.917676
2,100267022990578563888527231462820232415,3.1,X,1,10,43740000,43757195,78.660050,134.469585,1.877078
3,100267022990578563888527231462820232415,3.1,X,1,12,51241370,51256067,78.686841,134.282074,2.027929
4,100267022990578563888527231462820232415,3.1,X,1,15,58747434,58759996,78.253423,133.644737,2.409235
...,...,...,...,...,...,...,...,...,...,...
1832751,99604416062120274931641911251862984356,2.1,17,1,52,73751388,73759983,71.962111,212.037365,2.676902
1832752,99604416062120274931641911251862984356,2.1,17,1,58,81246004,81259969,71.226009,211.825336,2.479248
1832753,99604416062120274931641911251862984356,2.1,17,1,61,84495097,84507590,71.126310,212.170183,2.135738
1832754,99604416062120274931641911251862984356,2.1,17,1,65,89346720,89359845,71.908791,211.205570,2.381380
1832755,99604416062120274931641911251862984356,2.1,17,1,67,90349499,90361278,71.901743,211.188607,2.830414

### Questions about traces

In [ ]:
def characterize_trace(df):
    s = pd.Series({
        'trace_start': df.chrom_order.min(), 'trace_end': df.chrom_order.max(),
        'trace_len': len(df), 'trace_nloci': df.chrom_order.max() + 1 - df.chrom_order.min(),
        'trace_nbp': df.chrom_end.max() - df.chrom_start.min()})
    return s
    

df_trace = df.groupby(['cell_id', 'chrom', 'trace_id']).apply(characterize_trace, include_groups=False).reset_index()
# df_trace.rename({0: 'nloci'}, axis=1, inplace=True)

#### 1. Does the trace_id correspond to the relative length of the trace, such that trace_id=1 is always longer than trace_id=2, etc? (→ NO!)

In [39]:
def compare_trace_for_chrom(df, compare_via='trace_len'):
    if df.trace_id.max() == 1:
        return None
    expected_trace_order = np.arange(1, df.trace_id.max() + 1)
    actual_trace_order = df.sort_values(compare_via, ascending=False).trace_id.values
    if np.array_equal(actual_trace_order, expected_trace_order):
        return None
    return df[expected_trace_order != actual_trace_order].reset_index(drop=True)


for compare_via in ('trace_len', 'trace_nloci', 'trace_nbp'):
    res = df_trace.groupby(['cell_id', 'chrom']).apply(compare_trace_for_chrom, include_groups=False, compare_via=compare_via).reset_index(
        level=[0, 1]).set_index(['cell_id', 'chrom'])
    print(f"{compare_via=}, num cell-chrom combos where lower-numbered traces don't have the most loci={len(res.index.drop_duplicates())}")
    print(res.trace_id.drop_duplicates().values)

# num_suprising_ordering = res.groupby(['cell_id', 'chrom']).size().reset_index()
# len(num_suprising_ordering.loc[num_suprising_ordering[0] != 2, 'cell_id'].drop_duplicates())

compare_via='trace_len', num cell-chrom combos where lower-numbered traces don't have the most loci=2169
[1 2 3 4 5]
compare_via='trace_nloci', num cell-chrom combos where lower-numbered traces don't have the most loci=2144
[1 2 3 4]
compare_via='trace_nbp', num cell-chrom combos where lower-numbered traces don't have the most loci=2311
[1 2 3 4]

#### 2. Are there ever totally non-overlapping (complementary) traces? (→ NO!)

In [80]:
def find_nonoverlapping_traces(df):
    if len(df) == 1:
        return None
    traces = df.trace_id.values
    df_overlap = []
    for i in traces:
        start_i, end_i = df.loc[df.trace_id == i, ['trace_start', 'trace_end']].values.ravel()
        for j in range(i + 1, traces.max()):
            start_j, end_j = df.loc[df.trace_id == j, ['trace_start', 'trace_end']].values.ravel()
            if (end_j < start_i) or (end_i < start_j):  # Traces don't overlap
                df_overlap.append({
                    'trace_id': [i, j][np.argmin([start_i, start_j])],
                    'trace_start': np.min([start_i, start_j]),
                    'trace_max': np.max([end_i, end_j])})
    if not len(df_overlap):
        return None
    return pd.Dataframe(df_overlap)


has_overlap = df_trace.groupby(['cell_id', 'chrom']).apply(find_nonoverlapping_traces, include_groups=False)
if not len(has_overlap):
    print("No non-overlapping traces!")
has_overlap

No non-overlapping traces!

Empty DataFrame
Columns: []
Index: []

#### 3. Further characterize traces

In [91]:
df_chrom_ntraces = df_trace.groupby(['cell_id', 'chrom']).size().reset_index().rename({0: 'ntraces'}, axis=1)
df_chrom_ntraces

                                       cell_id chrom  ntraces
0      100248997715285942293181957009945158269    12        1
1      100248997715285942293181957009945158269     4        1
2      100267022990578563888527231462820232415    17        1
3      100267022990578563888527231462820232415    18        1
4      100267022990578563888527231462820232415     2        1
...                                        ...   ...      ...
30448   99885450568263402858676742529872331188    18        1
30449   99885450568263402858676742529872331188    19        1
30450   99885450568263402858676742529872331188     2        1
30451   99885450568263402858676742529872331188     5        1
30452   99885450568263402858676742529872331188     8        1

[30453 rows x 3 columns]

In [119]:
# for ntraces in df_cell_desc_chrom.ntraces.drop_duplicates().values
ntraces_types = {
    '1 trace': df_chrom_ntraces.ntraces == 1,
    '2 traces': df_chrom_ntraces.ntraces == 2,
    '>2 traces': df_chrom_ntraces.ntraces > 2}

df_chrom_ntraces[df_chrom_ntraces.ntraces > 2].groupby('cell_id').size().value_counts().sum()

df_chrom_ntraces[df_chrom_ntraces.ntraces == 2].groupby('cell_id').size().value_counts()

1     564
2     290
3     208
4     138
5     108
6      99
8      61
7      60
9      52
10     39
11     29
13     21
14     18
12     16
16     10
15     10
17      8
18      5
Name: count, dtype: int64

In [90]:
df_cell_desc_gt2trace = df_chrom_ntraces[df_chrom_ntraces.ntraces > 2].groupby('cell_id').size().reset_index().rename({0: 'nchrom_gt2trace'}, axis=1).sort_values(
    'nchrom_gt2trace', ascending=False)
print(df_cell_desc_gt2trace.nchrom_gt2trace.sum())
print(len(df_cell_desc_gt2trace))
print((df_cell_desc_gt2trace.nchrom_gt2trace > 1).sum())
df_cell_desc_gt2trace

200
99
34

                                    cell_id  nchrom_gt2trace
49  236707373299231246192523599949109740194               15
92     796907248109666331037430947342595009                7
42  211682870950575149725950043686209170640                7
87   57089633890354238603235644175840384596                7
57  266648537481793942323173786920475723304                7
..                                      ...              ...
36  202495501063792655693561618949921176863                1
35  201213478246125381219227212572258749785                1
34  201069040844675365475257195673380437661                1
32  197940930151083433626300695622139959148                1
98   94323664932217612227889992620571925771                1

[99 rows x 2 columns]

In [86]:
df_cell_desc_2trace = df_chrom_ntraces[df_chrom_ntraces.ntraces == 2].groupby('cell_id').size().reset_index().rename({0: 'nchrom_2trace'}, axis=1).sort_values(
    'nchrom_2trace', ascending=False)

print(df_cell_desc_2trace.nchrom_2trace.max())
print(len(df_cell_desc_2trace))
print(len(df_cell_desc_2trace[df_cell_desc_2trace.nchrom_2trace >= 2]))
print(len(df_cell_desc_2trace[df_cell_desc_2trace.nchrom_2trace >= 10]))
print(len(df_cell_desc_2trace[df_cell_desc_2trace.nchrom_2trace >= 15]))
print(len(df_cell_desc_2trace[df_cell_desc_2trace.nchrom_2trace >= 18]))

18
1736
1172
156
33
5

In [89]:
df_chrom_2trace = df_chrom_ntraces[df_chrom_ntraces.ntraces == 2].groupby('chrom').size().reset_index().rename({0: 'ncell_2trace'}, axis=1).sort_values(
    'ncell_2trace', ascending=False)

df_chrom_2trace

   chrom  ncell_2trace
1     10           497
12     3           476
17     8           425
13     4           420
14     5           413
9     18           397
3     12           368
4     13           367
5     14           357
15     6           349
0      1           348
16     7           328
8     17           318
6     15           313
18     9           290
7     16           290
2     11           288
10    19           280
11     2           264
19     X             4

### Question: are any of the imaged loci missing in all cells? (→NO!)

In [150]:
def find_missing_loci(df):
    if len(df) == df.chrom_order.max() + 1 - df.chrom_order.min():
        return False
    return True

chrom_has_missing_loci = df[['chrom', 'chrom_order']].drop_duplicates().groupby('chrom').apply(find_missing_loci, include_groups=False)
chrom_has_missing_loci.sum()

0

### Question: do some cells really have >2 copies of the same exact locus? (→YES!)

In [92]:
def count_occurances_of_locus(df, n_traces):
    s = pd.Series({'ncopies': len(df), 'ncells': len(df.cell_id.drop_duplicates())})
    for i in range(1, n_traces + 1):
        s[f'ncells_{i}copies'] = (df.groupby('cell_id').size() == i).sum()
    s['ncells_min2copies'] = (df.groupby('cell_id').size() >= 2).sum()
    return s

def add_missing_loci(df):
    if len(df) == df.chrom_order.max() + 1 - df.chrom_order.min():
        return df
    bins_all = np.arange(df.chrom_order.min(), df.chrom_order.max() + 1, dtype=int)
    is_missing = np.isin(bins_all, df.chrom_order.values, assume_unique=True, invert=True)

    df_missing = pd.DataFrame()
    df_missing['chrom_order'] = bins_all[is_missing]
    df_full = pd.concat([df, df_missing]).sort_values('chrom_order').fillna(0).reset_index(drop=True)
    for col in df.columns:
        df_full[col] = df_full[col].astype(int)
    return df_full


# per_locus = df.groupby(['chrom', 'chrom_order']).size().reset_index()
# per_locus.rename({0: 'ncopies'}, axis=1, inplace=True)
# # per_locus = per_locus.drop(index=[1, 3]).reset_index(drop=True) # FIXME remove, just for testing
# per_locus = per_locus.groupby('chrom').apply(add_missing_loci, include_groups=False).reset_index(level=0)
# per_locus['ncopies'].describe()

n_traces = df.trace_id.max()
per_locus = df.groupby(['chrom', 'chrom_order']).apply(count_occurances_of_locus, include_groups=False, n_traces=n_traces).reset_index()
for i in range(1, n_traces + 1):
    print(i, per_locus[f'ncells_{i}copies'].sum())
    if per_locus[f'ncells_{i}copies'].sum() == 0:
        per_locus.drop(f'ncells_{i}copies', axis=1)
per_locus = per_locus.groupby('chrom').apply(add_missing_loci, include_groups=False).reset_index(level=0)
print(per_locus['ncopies'].describe())
per_locus

1 1465881
2 178722
3 2863
4 188
5 18
count    1981.000000
mean      925.167087
std       222.108784
min        64.000000
25%       805.000000
50%       932.000000
75%      1065.000000
max      1896.000000
Name: ncopies, dtype: float64

,chrom,chrom_order,ncopies,ncells,ncells_1copies,ncells_2copies,ncells_3copies,ncells_4copies,ncells_5copies,ncells_min2copies
0,1,0,1133,1001,872,126,3,0,0,129
1,1,1,840,758,677,80,1,0,0,81
2,1,2,616,577,538,39,0,0,0,39
3,1,3,956,853,751,101,1,0,0,102
4,1,4,791,733,675,58,0,0,0,58
...,...,...,...,...,...,...,...,...,...,...
1976,X,59,388,388,388,0,0,0,0,0
1977,X,60,423,420,417,3,0,0,0,3
1978,X,61,416,413,410,3,0,0,0,3
1979,X,62,401,400,399,1,0,0,0,1
1980,X,63,560,557,554,3,0,0,0,3

### Process data manually

#### Filter data

In [4]:
df_filter = df

len(df_filter), len(df_filter) / len(df)

(1832756, 1.0)

In [5]:
# Remove small traces
min_nloci = 2
min_nloci_ratio = 0.1

def remove_small_traces(df, nloci_per_chrom, min_nloci=2, min_nloci_ratio=0.1):
    df['cutoff'] = np.maximum(min_nloci, min_nloci_ratio * nloci_per_chrom.loc[df.chrom.values].values)
    df = df.groupby('chrom').apply(lambda x: (x if len(x) > x.cutoff.values[0] else None), include_groups=False).reset_index(level=0)
    if len(df):
        return df.drop('cutoff', axis=1)


nloci_per_chrom = df_filter[['chrom', 'chrom_order']].drop_duplicates().groupby('chrom').size()

df_filter = df_filter.groupby(['cell_id', 'trace_id']).apply(
    remove_small_traces, include_groups=False, nloci_per_chrom=nloci_per_chrom,
    min_nloci=min_nloci, min_nloci_ratio=min_nloci_ratio).reset_index(level=[0, 1])

if len(df_filter) == len(df): # Save memory, if possible
    df_filter = df

print(len(df_filter), len(df_filter) / len(df))

1832756 1.0

In [6]:
# # Remove cells with where all chromosomes only have 1 trace

# df_filter = df_filter.groupby('cell_id').apply(lambda x: (None if len(x.trace_id.drop_duplicates()) == 1 else x), include_groups=False).reset_index(level=0)

# if len(df_filter) == len(df): # Save memory, if possible
#     df_filter = df

# print(len(df_filter), len(df_filter) / len(df))

In [7]:
# Remove cells where >[cutoff] chromosomes have >2 traces
max_nchrom = 0

def remove_cells_with_extra_traces(df, max_nchrom=1):
    nchrom_with_extra_traces = df.groupby('chrom').apply(
        lambda x: len(x.trace_id.drop_duplicates()) > 2, include_groups=False).sum()
    if nchrom_with_extra_traces <= max_nchrom:
        return df


df_filter = df_filter.groupby('cell_id').apply(
    remove_cells_with_extra_traces, include_groups=False, max_nchrom=max_nchrom).reset_index(level=0)

print(len(df_filter), len(df_filter) / len(df))

1702122 0.9287226450220324

In [8]:
# Remove chromosomes with where no cells have >1 trace

df_filter = df_filter.groupby('chrom').apply(lambda x: (None if len(x.trace_id.drop_duplicates()) == 1 else x), include_groups=False).reset_index(level=0)

print(len(df_filter), len(df_filter) / len(df))

df_filter.chrom.drop_duplicates().astype(int).sort_values().values

1679560 0.9164122229036489

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [9]:
df_filter.set_index(['cell_id', 'chrom', 'chrom_order'], inplace=True)
has_2traces_idx = df_filter[df_filter.trace_id == 1].index.intersection(df_filter[df_filter.trace_id == 2].index)
df_filter['ntraces'] = 1
df_filter.loc[has_2traces_idx, 'ntraces'] = 2
df_filter.reset_index(inplace=True)
print(len(has_2traces_idx), (df_filter.ntraces == 2).sum() / 2)

156044 156044.0

#### Sort cells for each chromosome

In [ ]:
def get_nloci_in_trace(df):
    return pd.Series({'nloci': len(df), 'nloci_2trace': (df.ntraces == 2).sum()})


# For each trace: nloci per trace + nloci that are on both traces in the given cell
df_cell_desc = df_filter.groupby(['cell_id', 'chrom', 'trace_id']).apply(
    get_nloci_in_trace, include_groups=False).reset_index(level=[2])

# For each cell: total nloci (summed across both traces) + difference in nloci between homolog
df_cell_desc['nloci_per_cell'] = df_cell_desc['nloci'].groupby(level=[0,1]).sum()
df_cell_desc['nloci_diff'] = df_cell_desc['nloci'].groupby(level=[0,1]).apply(
    lambda x: (-np.inf if len(x) == 1 else -np.abs(x.values[0] - x.values[1])), include_groups=False)
df_cell_desc.reset_index(level=[0,1], inplace=True)

cols_to_sort = ['nloci_2trace', 'nloci_per_cell', 'nloci_diff']
df_cell_desc = df_cell_desc.groupby(['cell_id', 'chrom'] + cols_to_sort).size().reset_index(
    level=[0, 1, 2, 3, 4]).rename({0: 'ntraces_in_cell'}, axis=1)

df_cell_desc.sort_values(['chrom', 'ntraces_in_cell'] + cols_to_sort, ascending=False, inplace=True)

df_cell_desc[df_cell_desc.ntraces_in_cell == 2]

#### Assign homolog identities for each cell

In [11]:
df_filter['hmlg'] = None
df_filter.sort_values(['chrom', 'cell_id', 'chrom_order'], inplace=True)

chromosomes = df_cell_desc.chrom.drop_duplicates().sort_values().values

df_filter

,cell_id,chrom,chrom_order,rep_id,trace_id,chrom_start,chrom_end,x,y,z,ntraces,hmlg
0,100471792397581761099150459290276466001,1,3,1.1,1,9627926,9637875,55.227186,55.175136,2.147975,1,None
1,100471792397581761099150459290276466001,1,4,1.1,1,9799472,9811359,54.958904,54.820563,1.728708,1,None
2,100471792397581761099150459290276466001,1,6,1.1,1,13741888,13757922,55.115618,55.337600,1.666775,1,None
3,100471792397581761099150459290276466001,1,7,1.1,1,16251322,16259969,53.962818,54.650339,1.426421,1,None
4,100471792397581761099150459290276466001,1,9,1.1,1,20920666,20929358,53.430811,55.130925,2.637035,1,None
...,...,...,...,...,...,...,...,...,...,...,...,...
1679555,99741185418064009670252552406571184121,9,92,3.1,1,111249941,111259901,150.400120,162.406161,3.769046,1,None
1679556,99741185418064009670252552406571184121,9,96,3.1,1,116249033,116259999,149.619452,161.750491,3.392094,1,None
1679557,99741185418064009670252552406571184121,9,97,3.1,1,118751319,118759956,149.284609,161.672195,3.582568,1,None
1679558,99741185418064009670252552406571184121,9,100,3.1,1,123457587,123467505,150.379762,161.954377,4.043290,1,None
1679559,99741185418064009670252552406571184121,9,101,3.1,1,123741973,123759929,150.155564,162.097330,3.666977,1,None

In [ ]:
from scipy.spatial.distance import pdist
from tqdm.notebook import tqdm


def disterror(struct_hmlg, struct_candidate):
    # While struct_hmlg only includes loci present in struct_candidate...
    # ...we need to make sure that struct_candidate only includes loci present in struct_hmlg
    # for this particular trace of this particular previously labeled cell
    struct_candidate = struct_candidate[struct_candidate.chrom_order.isin(
        struct_hmlg.chrom_order)]
    dis_candidate = pdist(struct_candidate[['x', 'y', 'z']].values)
    dis_hmlg = pdist(struct_hmlg[['x', 'y', 'z']].values)
    # Take the sum of the squared error and record the number of bins ('n') so that
    # we can more easily aggregate data across previously labeled cells
    # (Don't want to take the mean of multiple MSE values since 'n' might differ per cell)
    return pd.Series({'err': np.square(dis_candidate - dis_hmlg).sum(), 'n': dis_hmlg.size})


chrom = chromosomes[0]

# List of cells that contain this chromosome
cells = df_cell_desc.loc[df_cell_desc.chrom == chrom, ['cell_id', 'ntraces_in_cell']].set_index(
    'cell_id').ntraces_in_cell

# Reset homolog identities for this chromosome
if 'hmlg' in df_filter.columns:
    df_filter.loc[df_filter.chrom == chrom, 'hmlg'] = None
else:
    df_filter['hmlg'] = None

# Arbitrarily label homologs of the first cell
mask = (df_filter.chrom == chrom) & (df_filter.cell_id == cells.index[0])
df_filter.loc[mask, 'hmlg'] = df_filter.loc[mask, 'trace_id']

# cells_dict_items = cells.to_dict().items()
for cell_id, ntraces in tqdm(cells.to_dict().items()):
    if cell_id == cells.index[0]:  # First cell has already been labeled
        continue

    df_chrom = df_filter[(df_filter.chrom == chrom)]

    # Get all traces for the candidate cell, only including loci present in all of the candidate cell's traces
    candidate = df_chrom.loc[(df_chrom.cell_id == cell_id) & (df_chrom.ntraces == ntraces)]
    candidate = [candidate.loc[
                 candidate.trace_id == trace_id,
                 ['chrom_order', 'x', 'y', 'z']] for trace_id in np.arange(1, ntraces + 1)]
    loci_candidate = candidate[0].chrom_order.values

    # Get all labeled traces from previous cells, only including loci present in all of the candidate cell's traces
    hmlgs = df_chrom.loc[(~df_chrom.hmlg.isnull()) & df_chrom.chrom_order.isin(
        loci_candidate), ['cell_id', 'hmlg', 'chrom_order', 'x', 'y', 'z']]

    # Calculate distance error between each candidate trace and the labeled traces from each previous cell
    res = [hmlgs.groupby(['cell_id', 'hmlg']).apply(
        disterror, include_groups=False, struct_candidate=x).groupby(level=1).sum() for x in candidate]
    res = [x.err / x.n for x in res]  # Get MSE of distance matrices per pairing of traces 

    # print('***')
    # for i in range(ntraces):
    #     print(i); print(res[i])

    # Indices that determine how the candidate cell's trace(s) get paired to the pre-labled hmlgs
    pairingA = np.arange(ntraces) + 1  # Pair trace1 to hmlg1 (and trace2 to hmlg2)
    pairingB = 3 - pairingA  # Pair trace1 to hmlg2 (and trace2 to hmlg1)
    # print(pairingA); print(pairingB)

    # Compare mean distance error for each pairing
    # (Can take the mean because the number of loci is the same for all traces in the candidate cell)
    resA = np.mean([res[i].loc[pairingA[i]] for i in range(ntraces)])
    resB = np.mean([res[i].loc[pairingB[i]] for i in range(ntraces)])

    # print(resA); print(resB)

    # pairing = [pairingA, pairingB][np.argmin([resA, resB])]
    # print(pairing)

    # Assign the homolog itentities to candidate cell based on min distance error of the pairings
    mask = (df_filter.chrom == chrom) & (df_filter.cell_id == cell_id)
    if resA <= resB:
        # print('A')
        df_filter.loc[mask, 'hmlg'] = df_filter.loc[mask, 'trace_id']
    else:
        # print('B')
        df_filter.loc[mask, 'hmlg'] = 3 - df_filter.loc[mask, 'trace_id']

  0%|          | 0/1438 [00:00<?, ?it/s]


- for the loci that are non-NaN in both homologs...
-

## Mapping DNA-MERFISH traces to homologs

### Test in this notebook

In [ ]:
import os
import re
import numpy as np
import pandas as pd
from scipy.spatial.distance import pdist
from parse_dna_merfish import process_data, summarize_labeling
from tqdm.notebook import tqdm


sample_dir = "~/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt"
clusters_dir = os.path.join(sample_dir, "all_reps", "cluster")

chosen_loci_file = os.path.join(sample_dir, "loci.spaced2500kb.csv")

cluster = "astro"
input_file = os.path.join(clusters_dir, f"{cluster}/dna_merfish.{cluster}.csv")
output_file = os.path.join(clusters_dir, f"{cluster}/dna_merfish.{cluster}.filtered.csv")

df_labeled3 = process_data(
    input_file, chosen_loci_file=chosen_loci_file, trace_min_nloci=3, trace_min_nloci_ratio=0.1, max_nchrom_gt2trace=0,
    compare_to_labeled_loci_with_2_traces=False, chrom_to_filter=1, verbose=True)

In [103]:
# ncells_labeled = summarize_labeling(df_labeled)
# print(ncells_labeled)
# print('\n' + ('=' * 30) + '\n')
# ncells_labeled2 = summarize_labeling(df_labeled2)
# print(ncells_labeled)

Pairings for cells with only 1 trace:
pairing  ncells
      A      98
      B    1021

Pairings for cells with 2 traces:
pairing  ncells
      A     147
      B     172
         trace_id  hmlg  ncells
pairing
A               1     1     245
A               2     2     147
B               1     2    1193
B               2     1     172

==============================

Pairings for cells with only 1 trace:
pairing  ncells
      A     133
      B     986

Pairings for cells with 2 traces:
pairing  ncells
      A     150
      B     169
         trace_id  hmlg  ncells
pairing
A               1     1     245
A               2     2     147
B               1     2    1193
B               2     1     172

### Submit to cluster

In [904]:
%%bash

sample_dir="$HOME/noble_lab/repos/Chromatin_Analysis_MOp/data/MOp_wt"
chosen_loci_file="$sample_dir/loci.spaced2500kb.csv"
allreps_dir="$sample_dir/all_reps"


sge_outdir="$allreps_dir/sge_out"
mkdir -p "$sge_outdir"

for cluster in $(ls "$allreps_dir/cluster"); do
    if [[ "$cluster" != "astro" ]]; then # FIXME
        echo -e "\n\n==== CLUSTER=$cluster"    
        merfish_file="$allreps_dir/cluster/$cluster/dna_merfish.$cluster.csv"
        for chrom in $(seq 1 19); do
            echo -e "\nCLUSTER=$cluster, CHROM=$chrom"    
            qsub -P sage -cwd -V -l h_rt=7:00:00,mfree=3G -o "$sge_outdir" -e "$sge_outdir" -N "$cluster.$chrom" -R y -b y \
            python parse_dna_merfish.py "$merfish_file" --chosen_loci "$chosen_loci_file" --chrom "$chrom" --verbose
        done
    fi # FIXME
done

==== CLUSTER=endo

CLUSTER=endo, CHROM=1
modified hard resource list of job 0
Your job 13114301 ("endo.1") has been submitted

CLUSTER=endo, CHROM=2
modified hard resource list of job 0
Your job 13114302 ("endo.2") has been submitted

CLUSTER=endo, CHROM=3
modified hard resource list of job 0
Your job 13114303 ("endo.3") has been submitted

CLUSTER=endo, CHROM=4
modified hard resource list of job 0
Your job 13114304 ("endo.4") has been submitted

CLUSTER=endo, CHROM=5
modified hard resource list of job 0
Your job 13114305 ("endo.5") has been submitted

CLUSTER=endo, CHROM=6
modified hard resource list of job 0
Your job 13114306 ("endo.6") has been submitted

CLUSTER=endo, CHROM=7
modified hard resource list of job 0
Your job 13114307 ("endo.7") has been submitted

CLUSTER=endo, CHROM=8
modified hard resource list of job 0
Your job 13114308 ("endo.8") has been submitted

CLUSTER=endo, CHROM=9
modified hard resource list of job 0
Your job 13114309 ("endo.9") has been submitted

CLUSTER=endo, CHROM=10
modified hard resource list of job 0
Your job 13114310 ("endo.10") has been submitted

CLUSTER=endo, CHROM=11
modified hard resource list of job 0
Your job 13114311 ("endo.11") has been submitted

CLUSTER=endo, CHROM=12
modified hard resource list of job 0
Your job 13114312 ("endo.12") has been submitted

CLUSTER=endo, CHROM=13
modified hard resource list of job 0
Your job 13114313 ("endo.13") has been submitted

CLUSTER=endo, CHROM=14
modified hard resource list of job 0
Your job 13114314 ("endo.14") has been submitted

CLUSTER=endo, CHROM=15
modified hard resource list of job 0
Your job 13114315 ("endo.15") has been submitted

CLUSTER=endo, CHROM=16
modified hard resource list of job 0
Your job 13114316 ("endo.16") has been submitted

CLUSTER=endo, CHROM=17
modified hard resource list of job 0
Your job 13114317 ("endo.17") has been submitted

CLUSTER=endo, CHROM=18
modified hard resource list of job 0
Your job 13114318 ("endo.18") has been submitted

CLUSTER=endo, CHROM=19
modified hard resource list of job 0
Your job 13114319 ("endo.19") has been submitted


==== CLUSTER=l2-3_it

CLUSTER=l2-3_it, CHROM=1
modified hard resource list of job 0
Your job 13114320 ("l2-3_it.1") has been submitted

CLUSTER=l2-3_it, CHROM=2
modified hard resource list of job 0
Your job 13114321 ("l2-3_it.2") has been submitted

CLUSTER=l2-3_it, CHROM=3
modified hard resource list of job 0
Your job 13114322 ("l2-3_it.3") has been submitted

CLUSTER=l2-3_it, CHROM=4
modified hard resource list of job 0
Your job 13114323 ("l2-3_it.4") has been submitted

CLUSTER=l2-3_it, CHROM=5
modified hard resource list of job 0
Your job 13114324 ("l2-3_it.5") has been submitted

CLUSTER=l2-3_it, CHROM=6
modified hard resource list of job 0
Your job 13114325 ("l2-3_it.6") has been submitted

CLUSTER=l2-3_it, CHROM=7
modified hard resource list of job 0
Your job 13114326 ("l2-3_it.7") has been submitted

CLUSTER=l2-3_it, CHROM=8
modified hard resource list of job 0
Your job 13114327 ("l2-3_it.8") has been submitted

CLUSTER=l2-3_it, CHROM=9
modified hard resource list of job 0
Your job 13114328 ("l2-3_it.9") has been submitted

CLUSTER=l2-3_it, CHROM=10
modified hard resource list of job 0
Your job 13114329 ("l2-3_it.10") has been submitted

CLUSTER=l2-3_it, CHROM=11
modified hard resource list of job 0
Your job 13114330 ("l2-3_it.11") has been submitted

CLUSTER=l2-3_it, CHROM=12
modified hard resource list of job 0
Your job 13114331 ("l2-3_it.12") has been submitted

CLUSTER=l2-3_it, CHROM=13
modified hard resource list of job 0
Your job 13114332 ("l2-3_it.13") has been submitted

CLUSTER=l2-3_it, CHROM=14
modified hard resource list of job 0
Your job 13114333 ("l2-3_it.14") has been submitted

CLUSTER=l2-3_it, CHROM=15
modified hard resource list of job 0
Your job 13114334 ("l2-3_it.15") has been submitted

CLUSTER=l2-3_it, CHROM=16
modified hard resource list of job 0
Your job 13114335 ("l2-3_it.16") has been submitted

CLUSTER=l2-3_it, CHROM=17
modified hard resource list of job 0
Your job 13114336 ("l2-3_it.17") has been submitted

CLUSTER=l2-3_it, CHROM=18
modified hard resource list of job 0
Your job 13114337 ("l2-3_it.18") has been submitted

CLUSTER=l2-3_it, CHROM=19
modified hard resource list of job 0
Your job 13114339 ("l2-3_it.19") has been submitted


==== CLUSTER=l4-5_it

CLUSTER=l4-5_it, CHROM=1
modified hard resource list of job 0
Your job 13114340 ("l4-5_it.1") has been submitted

CLUSTER=l4-5_it, CHROM=2
modified hard resource list of job 0
Your job 13114341 ("l4-5_it.2") has been submitted

CLUSTER=l4-5_it, CHROM=3
modified hard resource list of job 0
Your job 13114343 ("l4-5_it.3") has been submitted

CLUSTER=l4-5_it, CHROM=4
modified hard resource list of job 0
Your job 13114344 ("l4-5_it.4") has been submitted

CLUSTER=l4-5_it, CHROM=5
modified hard resource list of job 0
Your job 13114345 ("l4-5_it.5") has been submitted

CLUSTER=l4-5_it, CHROM=6
modified hard resource list of job 0
Your job 13114346 ("l4-5_it.6") has been submitted

CLUSTER=l4-5_it, CHROM=7
modified hard resource list of job 0
Your job 13114347 ("l4-5_it.7") has been submitted

CLUSTER=l4-5_it, CHROM=8
modified hard resource list of job 0
Your job 13114348 ("l4-5_it.8") has been submitted

CLUSTER=l4-5_it, CHROM=9
modified hard resource list of job 0
Your job 13114349 ("l4-5_it.9") has been submitted

CLUSTER=l4-5_it, CHROM=10
modified hard resource list of job 0
Your job 13114350 ("l4-5_it.10") has been submitted

CLUSTER=l4-5_it, CHROM=11
modified hard resource list of job 0
Your job 13114351 ("l4-5_it.11") has been submitted

CLUSTER=l4-5_it, CHROM=12
modified hard resource list of job 0
Your job 13114352 ("l4-5_it.12") has been submitted

CLUSTER=l4-5_it, CHROM=13
modified hard resource list of job 0
Your job 13114353 ("l4-5_it.13") has been submitted

CLUSTER=l4-5_it, CHROM=14
modified hard resource list of job 0
Your job 13114354 ("l4-5_it.14") has been submitted

CLUSTER=l4-5_it, CHROM=15
modified hard resource list of job 0
Your job 13114355 ("l4-5_it.15") has been submitted

CLUSTER=l4-5_it, CHROM=16
modified hard resource list of job 0
Your job 13114356 ("l4-5_it.16") has been submitted

CLUSTER=l4-5_it, CHROM=17
modified hard resource list of job 0
Your job 13114357 ("l4-5_it.17") has been submitted

CLUSTER=l4-5_it, CHROM=18
modified hard resource list of job 0
Your job 13114358 ("l4-5_it.18") has been submitted

CLUSTER=l4-5_it, CHROM=19
modified hard resource list of job 0
Your job 13114359 ("l4-5_it.19") has been submitted


==== CLUSTER=l5_it

CLUSTER=l5_it, CHROM=1
modified hard resource list of job 0
Your job 13114360 ("l5_it.1") has been submitted

CLUSTER=l5_it, CHROM=2
modified hard resource list of job 0
Your job 13114361 ("l5_it.2") has been submitted

CLUSTER=l5_it, CHROM=3
modified hard resource list of job 0
Your job 13114362 ("l5_it.3") has been submitted

CLUSTER=l5_it, CHROM=4
modified hard resource list of job 0
Your job 13114363 ("l5_it.4") has been submitted

CLUSTER=l5_it, CHROM=5
modified hard resource list of job 0
Your job 13114364 ("l5_it.5") has been submitted

CLUSTER=l5_it, CHROM=6
modified hard resource list of job 0
Your job 13114365 ("l5_it.6") has been submitted

CLUSTER=l5_it, CHROM=7
modified hard resource list of job 0
Your job 13114366 ("l5_it.7") has been submitted

CLUSTER=l5_it, CHROM=8
modified hard resource list of job 0
Your job 13114367 ("l5_it.8") has been submitted

CLUSTER=l5_it, CHROM=9
modified hard resource list of job 0
Your job 13114368 ("l5_it.9") has been submitted

CLUSTER=l5_it, CHROM=10
modified hard resource list of job 0
Your job 13114369 ("l5_it.10") has been submitted

CLUSTER=l5_it, CHROM=11
modified hard resource list of job 0
Your job 13114370 ("l5_it.11") has been submitted

CLUSTER=l5_it, CHROM=12
modified hard resource list of job 0
Your job 13114371 ("l5_it.12") has been submitted

CLUSTER=l5_it, CHROM=13
modified hard resource list of job 0
Your job 13114372 ("l5_it.13") has been submitted

CLUSTER=l5_it, CHROM=14
modified hard resource list of job 0
Your job 13114373 ("l5_it.14") has been submitted

CLUSTER=l5_it, CHROM=15
modified hard resource list of job 0
Your job 13114374 ("l5_it.15") has been submitted

CLUSTER=l5_it, CHROM=16
modified hard resource list of job 0
Your job 13114375 ("l5_it.16") has been submitted

CLUSTER=l5_it, CHROM=17
modified hard resource list of job 0
Your job 13114376 ("l5_it.17") has been submitted

CLUSTER=l5_it, CHROM=18
modified hard resource list of job 0
Your job 13114377 ("l5_it.18") has been submitted

CLUSTER=l5_it, CHROM=19
modified hard resource list of job 0
Your job 13114378 ("l5_it.19") has been submitted


==== CLUSTER=l6_ct

CLUSTER=l6_ct, CHROM=1
modified hard resource list of job 0
Your job 13114379 ("l6_ct.1") has been submitted

CLUSTER=l6_ct, CHROM=2
modified hard resource list of job 0
Your job 13114380 ("l6_ct.2") has been submitted

CLUSTER=l6_ct, CHROM=3
modified hard resource list of job 0
Your job 13114381 ("l6_ct.3") has been submitted

CLUSTER=l6_ct, CHROM=4
modified hard resource list of job 0
Your job 13114382 ("l6_ct.4") has been submitted

CLUSTER=l6_ct, CHROM=5
modified hard resource list of job 0
Your job 13114383 ("l6_ct.5") has been submitted

CLUSTER=l6_ct, CHROM=6
modified hard resource list of job 0
Your job 13114384 ("l6_ct.6") has been submitted

CLUSTER=l6_ct, CHROM=7
modified hard resource list of job 0
Your job 13114385 ("l6_ct.7") has been submitted

CLUSTER=l6_ct, CHROM=8
modified hard resource list of job 0
Your job 13114386 ("l6_ct.8") has been submitted

CLUSTER=l6_ct, CHROM=9
modified hard resource list of job 0
Your job 13114387 ("l6_ct.9") has been submitted

CLUSTER=l6_ct, CHROM=10
modified hard resource list of job 0
Your job 13114388 ("l6_ct.10") has been submitted

CLUSTER=l6_ct, CHROM=11
modified hard resource list of job 0
Your job 13114389 ("l6_ct.11") has been submitted

CLUSTER=l6_ct, CHROM=12
modified hard resource list of job 0
Your job 13114390 ("l6_ct.12") has been submitted

CLUSTER=l6_ct, CHROM=13
modified hard resource list of job 0
Your job 13114391 ("l6_ct.13") has been submitted

CLUSTER=l6_ct, CHROM=14
modified hard resource list of job 0
Your job 13114392 ("l6_ct.14") has been submitted

CLUSTER=l6_ct, CHROM=15
modified hard resource list of job 0
Your job 13114393 ("l6_ct.15") has been submitted

CLUSTER=l6_ct, CHROM=16
modified hard resource list of job 0
Your job 13114394 ("l6_ct.16") has been submitted

CLUSTER=l6_ct, CHROM=17
modified hard resource list of job 0
Your job 13114395 ("l6_ct.17") has been submitted

CLUSTER=l6_ct, CHROM=18
modified hard resource list of job 0
Your job 13114396 ("l6_ct.18") has been submitted

CLUSTER=l6_ct, CHROM=19
modified hard resource list of job 0
Your job 13114397 ("l6_ct.19") has been submitted


==== CLUSTER=l6_it

CLUSTER=l6_it, CHROM=1
modified hard resource list of job 0
Your job 13114398 ("l6_it.1") has been submitted

CLUSTER=l6_it, CHROM=2
modified hard resource list of job 0
Your job 13114399 ("l6_it.2") has been submitted

CLUSTER=l6_it, CHROM=3
modified hard resource list of job 0
Your job 13114400 ("l6_it.3") has been submitted

CLUSTER=l6_it, CHROM=4
modified hard resource list of job 0
Your job 13114401 ("l6_it.4") has been submitted

CLUSTER=l6_it, CHROM=5
modified hard resource list of job 0
Your job 13114402 ("l6_it.5") has been submitted

CLUSTER=l6_it, CHROM=6
modified hard resource list of job 0
Your job 13114403 ("l6_it.6") has been submitted

CLUSTER=l6_it, CHROM=7
modified hard resource list of job 0
Your job 13114404 ("l6_it.7") has been submitted

CLUSTER=l6_it, CHROM=8
modified hard resource list of job 0
Your job 13114405 ("l6_it.8") has been submitted

CLUSTER=l6_it, CHROM=9
modified hard resource list of job 0
Your job 13114406 ("l6_it.9") has been submitted

CLUSTER=l6_it, CHROM=10
modified hard resource list of job 0
Your job 13114407 ("l6_it.10") has been submitted

CLUSTER=l6_it, CHROM=11
modified hard resource list of job 0
Your job 13114408 ("l6_it.11") has been submitted

CLUSTER=l6_it, CHROM=12
modified hard resource list of job 0
Your job 13114409 ("l6_it.12") has been submitted

CLUSTER=l6_it, CHROM=13
modified hard resource list of job 0
Your job 13114410 ("l6_it.13") has been submitted

CLUSTER=l6_it, CHROM=14
modified hard resource list of job 0
Your job 13114411 ("l6_it.14") has been submitted

CLUSTER=l6_it, CHROM=15
modified hard resource list of job 0
Your job 13114412 ("l6_it.15") has been submitted

CLUSTER=l6_it, CHROM=16
modified hard resource list of job 0
Your job 13114413 ("l6_it.16") has been submitted

CLUSTER=l6_it, CHROM=17
modified hard resource list of job 0
Your job 13114414 ("l6_it.17") has been submitted

CLUSTER=l6_it, CHROM=18
modified hard resource list of job 0
Your job 13114415 ("l6_it.18") has been submitted

CLUSTER=l6_it, CHROM=19
modified hard resource list of job 0
Your job 13114416 ("l6_it.19") has been submitted


==== CLUSTER=oligo

CLUSTER=oligo, CHROM=1
modified hard resource list of job 0
Your job 13114417 ("oligo.1") has been submitted

CLUSTER=oligo, CHROM=2
modified hard resource list of job 0
Your job 13114418 ("oligo.2") has been submitted

CLUSTER=oligo, CHROM=3
modified hard resource list of job 0
Your job 13114419 ("oligo.3") has been submitted

CLUSTER=oligo, CHROM=4
modified hard resource list of job 0
Your job 13114420 ("oligo.4") has been submitted

CLUSTER=oligo, CHROM=5
modified hard resource list of job 0
Your job 13114421 ("oligo.5") has been submitted

CLUSTER=oligo, CHROM=6
modified hard resource list of job 0
Your job 13114422 ("oligo.6") has been submitted

CLUSTER=oligo, CHROM=7
modified hard resource list of job 0
Your job 13114423 ("oligo.7") has been submitted

CLUSTER=oligo, CHROM=8
modified hard resource list of job 0
Your job 13114424 ("oligo.8") has been submitted

CLUSTER=oligo, CHROM=9
modified hard resource list of job 0
Your job 13114425 ("oligo.9") has been submitted

CLUSTER=oligo, CHROM=10
modified hard resource list of job 0
Your job 13114426 ("oligo.10") has been submitted

CLUSTER=oligo, CHROM=11
modified hard resource list of job 0
Your job 13114427 ("oligo.11") has been submitted

CLUSTER=oligo, CHROM=12
modified hard resource list of job 0
Your job 13114428 ("oligo.12") has been submitted

CLUSTER=oligo, CHROM=13
modified hard resource list of job 0
Your job 13114429 ("oligo.13") has been submitted

CLUSTER=oligo, CHROM=14
modified hard resource list of job 0
Your job 13114430 ("oligo.14") has been submitted

CLUSTER=oligo, CHROM=15
modified hard resource list of job 0
Your job 13114431 ("oligo.15") has been submitted

CLUSTER=oligo, CHROM=16
modified hard resource list of job 0
Your job 13114432 ("oligo.16") has been submitted

CLUSTER=oligo, CHROM=17
modified hard resource list of job 0
Your job 13114433 ("oligo.17") has been submitted

CLUSTER=oligo, CHROM=18
modified hard resource list of job 0
Your job 13114434 ("oligo.18") has been submitted

CLUSTER=oligo, CHROM=19
modified hard resource list of job 0
Your job 13114435 ("oligo.19") has been submitted

In [905]:
%%bash

gcq stat x

12958333	r  04/08...00:19p JUPYTER.mf 0
13114301	r 04:25p endo.1 0
13114302	r 04:25p endo.2 0
13114303	r 04:25p endo.3 0
13114304	r 04:25p endo.4 0
13114305	r 04:25p endo.5 0
13114306	r 04:25p endo.6 0
13114307	r 04:25p endo.7 0
13114308	r 04:25p endo.8 0
13114309	r 04:25p endo.9 0
13114310	r 04:25p endo.10 0
13114311	r 04:25p endo.11 0
13114312	r 04:25p endo.12 0
13114313	r 04:25p endo.13 0
13114314	r 04:25p endo.14 0
13114315	r 04:25p endo.15 0
13114316	r 04:25p endo.16 0
13114317	r 04:25p endo.17 0
13114318	r 04:25p endo.18 0
13114319	r 04:25p endo.19 0
13114320	r 04:25p l2-3_it.1 0
13114321	r 04:25p l2-3_it.2 0
13114322	r 04:25p l2-3_it.3 0
13114323	r 04:25p l2-3_it.4 0
13114324	r 04:25p l2-3_it.5 0
13114325	r 04:25p l2-3_it.6 0
13114326	r 04:25p l2-3_it.7 0
13114327	r 04:25p l2-3_it.8 0
13114328	r 04:25p l2-3_it.9 0
13114329	r 04:25p l2-3_it.10 0
13114330	r 04:25p l2-3_it.11 0
13114331	r 04:25p l2-3_it.12 0
13114332	r 04:25p l2-3_it.13 0
13114333	r 04:25p l2-3_it.14 0
13114334	r 04:25p l2-3_it.15 0
13114335	r 04:25p l2-3_it.16 0
13114336	r 04:25p l2-3_it.17 0
13114337	r 04:25p l2-3_it.18 0
13114339	r 04:25p l2-3_it.19 0
13114340	r 04:25p l4-5_it.1 0
13114341	r 04:25p l4-5_it.2 0
13114343	r 04:25p l4-5_it.3 0
13114344	r 04:25p l4-5_it.4 0
13114345	r 04:25p l4-5_it.5 0
13114346	r 04:25p l4-5_it.6 0
13114347	r 04:25p l4-5_it.7 0
13114348	r 04:25p l4-5_it.8 0
13114349	r 04:25p l4-5_it.9 0
13114350	r 04:25p l4-5_it.10 0
13114351	r 04:25p l4-5_it.11 0
13114352	r 04:25p l4-5_it.12 0
13114353	r 04:25p l4-5_it.13 0
13114354	r 04:25p l4-5_it.14 0
13114355	r 04:25p l4-5_it.15 0
13114356	r 04:25p l4-5_it.16 0
13114357	r 04:25p l4-5_it.17 0
13114358	r 04:25p l4-5_it.18 0
13114359	r 04:25p l4-5_it.19 0
13114360	r 04:25p l5_it.1 0
13114361	r 04:25p l5_it.2 0
13114362	r 04:25p l5_it.3 0
13114363	r 04:25p l5_it.4 0
13114364	r 04:25p l5_it.5 0
13114365	r 04:25p l5_it.6 0
13114366	r 04:25p l5_it.7 0
13114367	r 04:25p l5_it.8 0
13114368	r 04:25p l5_it.9 0
13114369	r 04:25p l5_it.10 0
13114370	r 04:25p l5_it.11 0
13114371	r 04:25p l5_it.12 0
13114372	r 04:26p l5_it.13 0
13114373	r 04:26p l5_it.14 0
13114374	r 04:26p l5_it.15 0
13114375	r 04:26p l5_it.16 0
13114376	r 04:26p l5_it.17 0
13114377	r 04:26p l5_it.18 0
13114378	r 04:26p l5_it.19 0
13114379	r 04:26p l6_ct.1 0
13114380	r 04:26p l6_ct.2 0
13114381	r 04:26p l6_ct.3 0
13114382	r 04:26p l6_ct.4 0
13114383	r 04:26p l6_ct.5 0
13114384	r 04:26p l6_ct.6 0
13114385	r 04:26p l6_ct.7 0
13114386	r 04:26p l6_ct.8 0
13114387	r 04:26p l6_ct.9 0
13114388	r 04:26p l6_ct.10 0
13114389	r 04:26p l6_ct.11 0
13114390	r 04:26p l6_ct.12 0
13114391	r 04:26p l6_ct.13 0
13114392	r 04:26p l6_ct.14 0
13114393	r 04:26p l6_ct.15 0
13114394	r 04:26p l6_ct.16 0
13114395	r 04:26p l6_ct.17 0
13109274	r 01:59p QLOGIN 0
13114080	r 04:18p astro.1 0
13114081	r 04:18p astro.2 0
13114082	r 04:18p astro.3 0
13114083	r 04:18p astro.4 0
13114084	r 04:18p astro.5 0
13114085	r 04:18p astro.6 0
13114086	r 04:18p astro.7 0
13114087	r 04:18p astro.8 0
13114088	r 04:18p astro.9 0
13114089	r 04:18p astro.10 0
13114090	r 04:18p astro.11 0
13114091	r 04:26p astro.12 0
13114092	r 04:26p astro.13 0
13114093	r 04:26p astro.14 0
13114094	r 04:26p astro.15 0
13114396	qw 04:26p l6_ct.18 -1
13114397	qw 04:26p l6_ct.19 -1
13114398	qw 04:26p l6_it.1 -1
13114399	qw 04:26p l6_it.2 -1
13114400	qw 04:26p l6_it.3 -1
13114401	qw 04:26p l6_it.4 -1
13114402	qw 04:26p l6_it.5 -1
13114403	qw 04:26p l6_it.6 -1
13114404	qw 04:26p l6_it.7 -1
13114405	qw 04:26p l6_it.8 -1
13114406	qw 04:26p l6_it.9 -1
13114407	qw 04:26p l6_it.10 -1
13114408	qw 04:26p l6_it.11 -1
13114409	qw 04:26p l6_it.12 -1
13114410	qw 04:26p l6_it.13 -1
13114411	qw 04:26p l6_it.14 -1
13114412	qw 04:26p l6_it.15 -1
13114413	qw 04:26p l6_it.16 -1
13114414	qw 04:26p l6_it.17 -1
13114415	qw 04:26p l6_it.18 -1
13114416	qw 04:26p l6_it.19 -1
13114417	qw 04:26p oligo.1 -1
13114418	qw 04:26p oligo.2 -1
13114419	qw 04:26p oligo.3 -1
13114420	qw 04:26p oligo.4 -1
13114421	qw 04:26p oligo.5 -1
13114422	qw 04:26p oligo.6 -1
13114423	qw 04:26p oligo.7 -1
13114424	qw 04:26p oligo.8 -1
13114425	qw 04:26p oligo.9 -1
13114426	qw 04:26p oligo.10 -1
13114427	qw 04:26p oligo.11 -1
13114428	qw 04:26p oligo.12 -1
13114429	qw 04:26p oligo.13 -1
13114430	qw 04:26p oligo.14 -1
13114431	qw 04:26p oligo.15 -1
13114432	qw 04:26p oligo.16 -1
13114433	qw 04:26p oligo.17 -1
13114434	qw 04:26p oligo.18 -1
13114435	qw 04:26p oligo.19 -1
13114095	qw 04:18p astro.16 -1
13114096	qw 04:18p astro.17 -1
13114097	qw 04:18p astro.18 -1
13114098	qw 04:18p astro.19 -1
waiting: 44	running: 110

# Should I do the homolog labeling on this data, or on data in which the loci are evenly spaced? (eg the extra loci added near TSS/superenhancers are ignored)